version: '3.8'
services:
  avito-shop-service:
    image: merch_shop
    container_name: avito-shop-service
    build: ./
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      PASSWORD_SALT: ${PASSWORD_SALT}
    networks:
      - internal
      
  db:
    restart: always
    image: postgres:16.0
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - internal

networks:
  internal:

volumes:
  db-data:


